# Project config file
global:
    img_size: 224
    max_seed_value: 20

# Define dataset specific parameters
olivine:
    input_data: "Data/Input_Data/processed_img_data/generator_input_data/thin_section_dataset"
    input_data_small: "Data/Input_Data/processed_img_data/generator_input_data/small_dataset" 
    class_1_img_folder: "Data/Input_Data/processed_img_data/Olivine_Images"
    class_0_img_folder: "Data/Input_Data/processed_img_data/Non_Olivine_Images"
    polygon_label_folder: "Data/Labels/olivine/polygon_label_files"
    voc_label_folder: "Data/Labels/olivine/voc_data/SegmentationClass"
cats_vs_dogs:
    input_data: "Data/Input_Data/other_datasets/cats_vs_dogs"
    class_1_img_folder: ""
    class_0_img_folder: ""
    polygon_label_folder: ""
    voc_label_folder: ""

# Define model specific parameters
base:
    last_conv_layer_name: "last_conv_layer"
vgg:
    last_conv_layer_name: "block5_conv3"

# Define xlsx file path
xlsx_results_filepath: "training_results.xlsx"
xlsx_input_split_filepath: "train_val_test_split.xlsx"