use_gpu: 1
parent_dir: "debugging"
dataset: "olivine"
model_type: "vgg"
early_fusion: 0
late_fusion: 0
verbose_metrics: 1
epochs: 45 
batch_size: 32 
learning_rate: 0.001
optimizer: "adam"
iou_threshold: 0.01
dropout_value: 0.2
regularization: 0
num_hidden_layers: 1
wand_api_key: "0faedda74fb94f1193e4db4bef4c31027efc978f"